### ISSUE TITLE
Trouble mounting `binfmt_misc` for Docker builds

### ISSUE THREAD

**Issue by lstellway** [catthehacker/docker_images#112]
Hello,

I'm currently using Gitea with the [Gitea act runner](https://gitea.com/gitea/act_runner). 
I have the following labels configured to run jobs:

```yml
  labels:
    - "ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest"
    - "ubuntu-22.04:docker://ghcr.io/catthehacker/ubuntu:act-22.04"
    - "ubuntu-20.04:docker://ghcr.io/catthehacker/ubuntu:act-20.04"
```

When trying to use the [docker/setup-qemu-action@v3](https://github.com/docker/setup-qemu-action) action to prepare the environment for cross-platform builds, I get the following error:

```txt
[command]/usr/bin/docker run --rm --privileged tonistiigi/binfmt:latest --install all
error: operation not permitted
cannot mount binfmt_misc filesystem at /proc/sys/fs/binfmt_misc

main.run
	/src/cmd/binfmt/main.go:183
main.main
	/src/cmd/binfmt/main.go:170
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1571
```

Anybody else have this issue? 
Any ideas how to get the mount working? 

I'm thinking it maybe has something to do with the Docker daemon running outside of this container's filesystem and not having permissions to write to the mount path..?

Here is a sample of my workflow:

```yml
name: release-tag

on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
```
