### ISSUE TITLE
seems like systemd is missing? or something something something devbox installer doesn't work

### ISSUE THREAD

**Issue by airtonix** [catthehacker/docker_images#119]
with the following workflow: 

```yml
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  packages: write
  
name: ReleaseManagement


jobs:
  Release:
    runs-on: ubuntu-22.04

    
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }} # e.g. v1.0.0
      version: ${{ steps.release.outputs.version }} # e.g. 1.0.0
      json: ${{ toJSON(steps.release.outputs) }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        if: ${{!github.event.act}}
        id: release-please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          release-type: go
          extra-files: |
            meta/package.go
      - id: release
        name: act interop
        run: |
          if [ "${{!github.event.act}}" == "false" ]; then
            echo "release_created=true" >> $GITHUB_OUTPUT
            echo "releases_created=true" >> $GITHUB_OUTPUT
            echo "tag_name=snapshot" >> $GITHUB_OUTPUT
            echo "version=snaphot" >> $GITHUB_OUTPUT
          else
            echo "release_created=${{ steps.release-please.outputs.release_created }}" >> $GITHUB_OUTPUT
            echo "releases_created=${{ steps.release-please.outputs.releases_created }}" >> $GITHUB_OUTPUT
            echo "tag_name=${{ steps.release-please.outputs.tag_name }}" >> $GITHUB_OUTPUT
            echo "version=${{ steps.release-please.outputs.version }}" >> $GITHUB_OUTPUT
          fi

  Build:
    if: needs.Release.outputs.releases_created

    runs-on: ubuntu-22.04
    needs: [Release]

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # - uses: docker/setup-buildx-action@v2
      # - name: Docker Login
      #   uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup jetpack devbox
        uses: jetpack-io/devbox-install-action@v0.7.0

      - name: Run GoReleaser
        env:
          registry: ${{ env.REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ !github.event.act }}" == "true" ]; then
            devbox run -- gorelease release --clean
          else
            devbox run -- gorelease build --clean --snapshot
          fi

```

with this `.actevent.json`

```json
{
  "act": true
}
```

and this command 

```shell
  act push \
    --platform ubuntu-22.04=catthehacker/ubuntu:full-latest \
    --eventpath .actevent.json \
    --workflows .github/workflows/release.yml \
    --job Build
```

i get this output: 

```shell
act push --platform ubuntu-22.04=catthehacker/ubuntu:full-latest --eventpath .actevent.json --workflows .github/workflows/release.yml --job Build
[ReleaseManagement/Release] 🚀  Start image=catthehacker/ubuntu:full-latest
INFO[0000] Parallel tasks (0) below minimum, setting to 1 
[ReleaseManagement/Release]   🐳  docker pull image=catthehacker/ubuntu:full-latest platform= username= forcePull=true
INFO[0002] Parallel tasks (0) below minimum, setting to 1 
[ReleaseManagement/Release]   🐳  docker create image=catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[ReleaseManagement/Release]   🐳  docker run image=catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[ReleaseManagement/Release]   🐳  docker exec cmd=[chown -R 1001:127 /mnt/Store/Projects/Mine/Github/bank-downloaders] user=0 workdir=
[ReleaseManagement/Release]   ☁  git clone 'https://github.com/google-github-actions/release-please-action' # ref=v3
[ReleaseManagement/Release] ⭐ Run Main act interop
[ReleaseManagement/Release]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/release] user= workdir=
[ReleaseManagement/Release]   ✅  Success - Main act interop
[ReleaseManagement/Release]   ⚙  ::set-output:: version=snaphot
[ReleaseManagement/Release]   ⚙  ::set-output:: release_created=true
[ReleaseManagement/Release]   ⚙  ::set-output:: releases_created=true
[ReleaseManagement/Release]   ⚙  ::set-output:: tag_name=snapshot
[ReleaseManagement/Release] Cleaning up container for job Release
[ReleaseManagement/Release] 🏁  Job succeeded
[ReleaseManagement/Build  ] 🚀  Start image=catthehacker/ubuntu:full-latest
INFO[0004] Parallel tasks (0) below minimum, setting to 1 
[ReleaseManagement/Build  ]   🐳  docker pull image=catthehacker/ubuntu:full-latest platform= username= forcePull=true
INFO[0006] Parallel tasks (0) below minimum, setting to 1 
[ReleaseManagement/Build  ]   🐳  docker create image=catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[ReleaseManagement/Build  ]   🐳  docker run image=catthehacker/ubuntu:full-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[chown -R 1001:127 /mnt/Store/Projects/Mine/Github/bank-downloaders] user=0 workdir=
[ReleaseManagement/Build  ]   ☁  git clone 'https://github.com/jetpack-io/devbox-install-action' # ref=v0.7.0
[ReleaseManagement/Build  ] ⭐ Run Pre setup jetpack devbox
[ReleaseManagement/Build  ]   ☁  git clone 'https://github.com/actions/cache' # ref=v3
[ReleaseManagement/Build  ]   ☁  git clone 'https://github.com/actions/cache' # ref=v3
[ReleaseManagement/Build  ]   ☁  git clone 'https://github.com/DeterminateSystems/nix-installer-action' # ref=v4
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ] ⭐ Run Pre Install nix
[ReleaseManagement/Build  ]   ✅  Success - Pre Install nix
[ReleaseManagement/Build  ]   ☁  git clone 'https://github.com/actions/cache' # ref=v3
[ReleaseManagement/Build  ]   ☁  git clone 'https://github.com/actions/cache' # ref=v3
[ReleaseManagement/Build  ]   ✅  Success - Pre setup jetpack devbox
[ReleaseManagement/Build  ] ⭐ Run Main actions/checkout@v3
[ReleaseManagement/Build  ]   🐳  docker cp src=/mnt/Store/Projects/Mine/Github/bank-downloaders/. dst=/mnt/Store/Projects/Mine/Github/bank-downloaders
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[chown -R 1001:127 /mnt/Store/Projects/Mine/Github/bank-downloaders] user=0 workdir=
[ReleaseManagement/Build  ]   ✅  Success - Main actions/checkout@v3
[ReleaseManagement/Build  ] ⭐ Run Main setup jetpack devbox
[ReleaseManagement/Build  ]   🐳  docker cp src=/home/zenobius/.cache/act/jetpack-io-devbox-install-action@v0.7.0/ dst=/var/run/act/actions/jetpack-io-devbox-install-action@v0.7.0/
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[chown -R 1001:127 /var/run/act/actions/jetpack-io-devbox-install-action@v0.7.0/] user=0 workdir=
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ] ⭐ Run Main Get devbox version
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1-composite-0.sh] user= workdir=
| Found devbox latest version 0.8.2.
[ReleaseManagement/Build  ]   ✅  Success - Main Get devbox version
[ReleaseManagement/Build  ]   ⚙  ::set-env:: latest_version=0.8.2
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ] ⭐ Run Main Mount devbox cli cache
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ]   🐳  docker cp src=/home/zenobius/.cache/act/actions-cache-restore@v3/ dst=/var/run/act/actions/actions-cache-restore@v3/
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[chown -R 1001:127 /var/run/act/actions/actions-cache-restore@v3/] user=0 workdir=
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[node /var/run/act/actions/actions-cache-restore@v3/dist/restore-only/index.js] user= workdir=
[ReleaseManagement/Build  ]   💬  ::debug::Resolved Keys:
[ReleaseManagement/Build  ]   💬  ::debug::["Linux-devbox-cli-0.8.2"]
[ReleaseManagement/Build  ]   💬  ::debug::Checking zstd --quiet --version
[ReleaseManagement/Build  ]   💬  ::debug::1.5.5
[ReleaseManagement/Build  ]   💬  ::debug::zstd version: 1.5.5
[ReleaseManagement/Build  ]   💬  ::debug::Resource Url: http://192.168.86.43:38721/_apis/artifactcache/cache?keys=Linux-devbox-cli-0.8.2&version=10c3673137184e8fc98ee7019556b49e59a4412bda7618d1ecdeb71d8913cc9a
[ReleaseManagement/Build  ]   ⚙  ***
[ReleaseManagement/Build  ]   💬  ::debug::Cache Result:
[ReleaseManagement/Build  ]   💬  ::debug::{"archiveLocation":"***","cacheKey":"linux-devbox-cli-0.8.2","result":"hit"}
[ReleaseManagement/Build  ]   💬  ::debug::Archive Path: /tmp/397c456e-f8f8-4241-aca7-c328ecdbbde2/cache.tzst
[ReleaseManagement/Build  ]   💬  ::debug::Use Azure SDK: false
[ReleaseManagement/Build  ]   💬  ::debug::Download concurrency: 8
[ReleaseManagement/Build  ]   💬  ::debug::Request timeout (ms): 30000
[ReleaseManagement/Build  ]   💬  ::debug::Cache segment download timeout mins env var: undefined
[ReleaseManagement/Build  ]   💬  ::debug::Segment download timeout (ms): 600000
[ReleaseManagement/Build  ]   💬  ::debug::Lookup only: false
| Cache Size: ~8 MB (8449799 B)
| [command]/usr/bin/tar -xf /tmp/397c456e-f8f8-4241-aca7-c328ecdbbde2/cache.tzst -P -C /mnt/Store/Projects/Mine/Github/bank-downloaders --use-compress-program unzstd
| Cache restored successfully
| Cache restored from key: linux-devbox-cli-0.8.2
[ReleaseManagement/Build  ]   ✅  Success - Main Mount devbox cli cache
[ReleaseManagement/Build  ]   ⚙  ::set-output:: cache-primary-key=Linux-devbox-cli-0.8.2
[ReleaseManagement/Build  ]   ⚙  ::set-output:: cache-matched-key=linux-devbox-cli-0.8.2
[ReleaseManagement/Build  ]   ⚙  ::set-output:: cache-hit=true
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ] ⭐ Run Main Configure nix access-tokens
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1-composite-5.sh] user= workdir=
[ReleaseManagement/Build  ]   ✅  Success - Main Configure nix access-tokens
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ] ⭐ Run Main Install nix
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ]   🐳  docker cp src=/home/zenobius/.cache/act/DeterminateSystems-nix-installer-action@v4/ dst=/var/run/act/actions/DeterminateSystems-nix-installer-action@v4/
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[chown -R 1001:127 /var/run/act/actions/DeterminateSystems-nix-installer-action@v4/] user=0 workdir=
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ] ⭐ Run Main Install Nix
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1-composite-6-composite-0.sh] user= workdir=
| Set NIX_INSTALLER_EXTRA_CONF=experimental-features = ca-derivations fetch-closure
| trusted-users = root 
| Set NIX_INSTALLER_URL=https://install.determinate.systems/nix?ci=github
| Set NIX_INSTALLER_LOGGER=pretty
| Set NIX_INSTALLER_DIAGNOSTIC_ENDPOINT=https://install.determinate.systems/nix/diagnostic
| Set NIX_INSTALLER_NO_CONFIRM=true
|   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
|                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 16008  100 16008    0     0   9717      0  0:00:01  0:00:01 --:--:-- 64032
| info: downloading installer https://install.determinate.systems/nix/tag/v0.14.0/nix-installer-x86_64-linux
| `nix-installer` needs to run as `root`, attempting to escalate now via `sudo`...
| Error: 
|    0: Planner error
|    1: Error executing action
|    2: Action `configure_init_service` errored
|    3: Could not detect systemd; you may be able to get up and running without systemd with `nix-installer install linux --init none`.
|       See https://github.com/DeterminateSystems/nix-installer#without-systemd-linux-only for documentation on usage and drawbacks.
| 
| Location:
|    src/cli/subcommand/install.rs:197
| 
| Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
| Run with RUST_BACKTRACE=full to include source snippets.
| 
| Consider reporting this error using this URL: https://github.com/DeterminateSystems/nix-installer/issues/new?title=%3Cautogenerated-issue%3E&body=%23%23+Error%0A%60%60%60%0AError%3A+%0A+++0%3A+Planner+error%0A+++1%3A+Error+executing+action%0A+++2%3A+Action+%60configure_init_service%60+errored%0A+++3%3A+Could+not+detect+systemd%3B+you+may+be+able+to+get+up+and+running+without+systemd+with+%60nix-installer+install+linux+--init+none%60.%0A++++++See+https%3A%2F%2Fgithub.com%2FDeterminateSystems%2Fnix-installer%23without-systemd-linux-only+for+documentation+on+usage+and+drawbacks.%0A%60%60%60%0A%0A%23%23+Metadata%0A%7Ckey%7Cvalue%7C%0A%7C--%7C--%7C%0A%7C**version**%7C0.14.0%7C%0A%7C**os**%7Clinux%7C%0A%7C**arch**%7Cx86_64%7C%0A
[ReleaseManagement/Build  ]   ❌  Failure - Main Install Nix
[ReleaseManagement/Build  ] exitcode '1': failure
[ReleaseManagement/Build  ]   ❌  Failure - Main Install nix
[ReleaseManagement/Build  ] exitcode '1': failure
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[node /var/run/act/workflow/hashfiles/index.js] user= workdir=
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[node /var/run/act/workflow/hashfiles/index.js] user= workdir=
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ]   ❌  Failure - Main setup jetpack devbox
[ReleaseManagement/Build  ] exitcode '1': failure
[ReleaseManagement/Build  ] ⭐ Run Post setup jetpack devbox
[ReleaseManagement/Build  ]   🐳  docker cp src=/home/zenobius/.cache/act/jetpack-io-devbox-install-action@v0.7.0/ dst=/var/run/act/actions/jetpack-io-devbox-install-action@v0.7.0/
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[chown -R 1001:127 /var/run/act/actions/jetpack-io-devbox-install-action@v0.7.0/] user=0 workdir=
[ReleaseManagement/Build  ] 'runs-on' key not defined in ReleaseManagement/Build
[ReleaseManagement/Build  ] ⭐ Run Post Install nix
[ReleaseManagement/Build  ]   🐳  docker cp src=/home/zenobius/.cache/act/DeterminateSystems-nix-installer-action@v4/ dst=/var/run/act/actions/DeterminateSystems-nix-installer-action@v4/
[ReleaseManagement/Build  ]   🐳  docker exec cmd=[chown -R 1001:127 /var/run/act/actions/DeterminateSystems-nix-installer-action@v4/] user=0 workdir=
[ReleaseManagement/Build  ]   ✅  Success - Post Install nix
[ReleaseManagement/Build  ]   ✅  Success - Post setup jetpack devbox
[ReleaseManagement/Build  ] 🏁  Job failed
Error: Job 'Build' failed
```
