### ISSUE TITLE
Trouble setting up Elixir project on ubuntu:full-20.04

### ISSUE THREAD

**Issue by dustinfarris** [catthehacker/docker_images#23]
I am running a job that works on GitHub but having issues when using act to run locally.

I am using 

```
🚀  Start image=ghcr.io/catthehacker/ubuntu:full-20.04
```

the job definition (leaving out some of it for brevity) is:

```
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: qa
    services:
      db:
        image: postgres:11.5
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dpi_qa
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24.0
          elixir-version: 1.12.0
      - run: mix deps.get --only qa
 ```

on the last step here (getting mix dependencies) I get an error:

```
[Cypress Tests/cypress-run]   ✅  Success - Setup Elixir
[Cypress Tests/cypress-run] ⭐  Run mix deps.get --only qa
[Cypress Tests/cypress-run]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /Users/pepsi/work/cdna_ui/workflow/2] user=
| warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
| * Getting scrivener_html (https://github.com/jaimeiniesta/scrivener_html.git - origin/relax_phoenix_dep)
| ** (File.Error) could not make directory (with -p) "/Users/pepsi/work/cdna_ui/deps/scrivener_html": no such file or directory
|     (elixir 1.12.0) lib/file.ex:316: File.mkdir_p!/1
|     (mix 1.12.0) lib/mix/scm/git.ex:98: Mix.SCM.Git.checkout/1
|     (mix 1.12.0) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
|     (mix 1.12.0) lib/mix/dep/converger.ex:190: Mix.Dep.Converger.all/9
|     (mix 1.12.0) lib/mix/dep/converger.ex:201: Mix.Dep.Converger.all/9
|     (mix 1.12.0) lib/mix/dep/converger.ex:123: Mix.Dep.Converger.all/7
|     (mix 1.12.0) lib/mix/dep/converger.ex:72: Mix.Dep.Converger.all/4
|     (mix 1.12.0) lib/mix/dep/converger.ex:51: Mix.Dep.Converger.converge/4
[Cypress Tests/cypress-run]   ❌  Failure - mix deps.get --only qa
Error: exit with `FAILURE`: 1
```

this error does not happen when I use the `ubuntu:act-20.04` image (however that image is missing some other deps I need elsewhere)
