### ISSUE TITLE
Allow installation of graphviz

### ISSUE THREAD

**Issue by HalosGhost** [catthehacker/docker_images#27]
Using the following job, I run into an error when the container tries to install `graphviz`:

```
  doxygen:
    name: doxygen
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz
```

<details>
<summary><code>act</code> output</summary>
<pre>
[CI/doxygen] 🚀  Start image=catthehacker/ubuntu:act-20.04
[CI/doxygen]   🐳  docker run image=catthehacker/ubuntu:act-20.04 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[CI/doxygen]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
[CI/doxygen]   🐳  docker cp src=snip/. dst=snip
[CI/doxygen]   🐳  docker exec cmd=[mkdir -p snip] user=
[CI/doxygen] ⭐  Run actions/checkout@v2
[CI/doxygen]   ✅  Success - actions/checkout@v2
[CI/doxygen] ⭐  Run Install Doxygen
[CI/doxygen]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail snip/workflow/1] user=
Reading package lists... Done
Building dependency tree
Reading state information... Done
| Package graphviz is not available, but is referred to by another package.
| This may mean that the package is missing, has been obsoleted, or
| is only available from another source
|
| E: Unable to locate package doxygen
| E: Package 'graphviz' has no installation candidate
[CI/doxygen]   ❌  Failure - Install Doxygen
Error: exit with `FAILURE`: 100
</pre>
</details>

I tried pulling the full image and running with it, but it ran into other (quite odd) issues (e.g., trying to setup mongo-db?).
